### PR TITLE
BLADE-242 Add actionable dynamic query sample

### PR DESCRIPTION
**Pull request by jrao**
BLADE-242 Add actionable dynamic query sample

### CODE REVIEW

**Comment by jrao** [comment]
@lawrence-lee Hey Lawrence, @david-truong thought this might be a useful BLADE sample. Please let me know if you have any questions.

**Comment by lawrence-lee** [comment]
@jrao Thanks for sending this. I''ll review this later today.

**Comment by lawrence-lee** [comment]
@jrao I was reading the documentation and would you be able to write an integration test for this? Like the one from BookmarkEntry?

**Comment by jrao** [comment]
I could write a simple integration test to assert that the query produces the expected result. But which BookmarkEntry test are you referring to? I found https://github.com/jrao/liferay-portal/blob/master/modules/apps/bookmarks/bookmarks-test/src/testIntegration but I'm not sure which test in particular you mean.

**Comment by lawrence-lee** [comment]
Yea a simple assert would be fine. Just to make sure the sample is still valid.

I'm looking here: https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/dynamic-query#actionable-dynamic-queries 

something like this? 

```
ActionableDynamicQuery actionableDynamicQuery = BookmarksEntryLocalServiceUtil.getActionableDynamicQuery();

actionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<BookmarksEntry>() {
       @Override
       public void performAction(BookmarksEntry bookmarksEntry) {
         Assert.assertNotNull(bookmarksEntry);

         count.increment();
       }
    });

actionableDynamicQuery.performActions();
```

**Comment by jrao** [comment]
I see what you mean. Sure, I'll add a test like that.

**Comment by lawrence-lee** [comment]
@jrao Don't worry about the `build.gradle` I'll wire it up to Liferay workspace so it'll make testing easier. I think if you just work on the actual test method, i can help with the wiring. Its a bit different than running integration tests in Liferay Portal. See https://github.com/liferay/liferay-blade-samples/blob/master/liferay-workspace/apps/service-builder/basic/basic-service/src/testIntegration/java/com/liferay/blade/samples/servicebuilder/service/test/BladeServiceBuilderIntegrationTest.java

**Comment by jrao** [comment]
@lawrence-lee Ok, sounds good.

**Comment by jrao** [comment]
@lawrence-lee I added a test skeleton (the ADQTest class). Let me know if you need anything else. I can revisit if necessary after you've added the wiring to make the test run.

**Comment by lawrence-lee** [comment]
reviewing..

**Comment by lawrence-lee** [comment]
sent here: https://github.com/jrao/liferay-blade-samples/pull/2#issuecomment-390665788

**Comment by jrao** [comment]
sent https://github.com/lawrence-lee/liferay-blade-samples/pull/52

**Pull request closed without merging**
