### PR TITLE
BLADE-457 Not needed since 7.1

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
hey @csierra, Is there something we're still missing in our sample? I'm still getting access denied when i try to access `http://localhost:8080/o/users/list/`

`Access denied to com.liferay.blade.samples.rest.UsersRestService#getUsers`

**Comment by csierra** [comment]
hey @lawrence-lee, 
it looks like you are trying to access the service using `guest` user. Liferay does not allow for that OOTB since 7.2 (if I recall correctly) for security reasons and you need to explitily add a `default` service access policy for your rest endpoint to be allowed or disable the check using `liferay.access.control.disable=true` as a property of the `@Component`. 
But I would rather not add anything like this in the template code lest we have a lot of modules out there that disable this check. Especially since in the sample we are using the local service, which performs no permission validation.

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Pull request closed without merging**
